ALTER TABLE map_points ADD COLUMN IF NOT EXISTS amenities TEXT;
ALTER TABLE map_points ADD COLUMN IF NOT EXISTS ai_summary TEXT;
ALTER TABLE map_points ADD COLUMN IF NOT EXISTS enriched_at TIMESTAMP;
