ALTER TABLE boats ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(160);
ALTER TABLE boats ADD COLUMN IF NOT EXISTS model VARCHAR(160);
ALTER TABLE boats ADD COLUMN IF NOT EXISTS beam_m DOUBLE PRECISION;
ALTER TABLE boats ADD COLUMN IF NOT EXISTS home_marina VARCHAR(255);
ALTER TABLE boats ADD COLUMN IF NOT EXISTS country VARCHAR(120);
ALTER TABLE boats ADD COLUMN IF NOT EXISTS photo_url TEXT;
